[package]
name = "find_projects"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
crossbeam-channel = "0.5.15"
ignore = { version = "0.4.23", features = ["simd-accel"] }
