[workspace]
resolver = "2"
members = [
    "scrap-images",
    "bag",
    "overloaded",
    "word-freq",
    "uptime",
    "uptime/config",
    "ticker",
    "ip",
    "evictmap",
    "pretty-xml",
    "unc",
    "logic",
    "qr",
    "xkcd_lock",
]

