[workspace]
members = [
    "scrap-images",
    "bag",
    "overloaded",
    "word-freq",
    "uptime",
    "uptime/config",
    "ticker",
    "ip",
    "evictmap",
    "pretty-xml",
    "unc",
]

[profile.dev.package.backtrace]
opt-level = 3

