[package]
name = "qr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.14", features = ["derive"] }
env_logger = "0.10.1"
image = "0.24.7"
log = "0.4.20"
qrcode = "0.13.0"
