[package]
name = "trurl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
color-eyre = "0.6.2"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
url = { version = "2.3.1", features = ["serde"] }
