[package]
name = "ip"
version = "0.1.0"
authors = ["jRimbault <jacques.rimbault@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.1.6", features = ["derive"] }
ureq = "2.5.0"
