[package]
name = "word-freq"
authors = ["jRimbault <jacques.rimbault@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.1.6", features = ["derive"] }
regex = "1.5.5"
priority-queue = "1.2.1"
rayon = "1.5.1"
crossbeam = "0.8.1"
